on:
  # Release on push to main
  # push:
  # branches: [main]

  # Release on manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Build and Update Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Build Process
        run: npm run build

      - name: Generate Documentation
        run: npm run docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist
            docs
            types

  release:
    # Variable syntax below assumes Linux/Mac but could be easily adapted to Windows
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Prevent the action from storing credentials in a way that's hard to override
          persist-credentials: false

      - name: Install dependencies
        run: npm install

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # Set the name, email, and URL with PAT
      - name: Set git credentials
        run: |
          git config user.name "SCAYLE"
          git config user.email "${{ vars.REPO_USER_EMAIL }}"
          git remote set-url origin "https://$REPO_PAT@github.com/scayle/components"
        env:
          REPO_PAT: ${{ secrets.REPO_PAT }}

      # Pass the token on the command line for publishing
      - name: Publish
        run: npm run release -- --token "$NPM_TOKEN"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
